### ISSUE TITLE
How to use both hifi and ONT reads together?

### ISSUE THREAD

**Issue by JhinAir** [ShunOuchi/GreenHill#13]
Hi,
as titled, I wonder how to use both hifi and ONT reads to do scaffolding? Is it good to directly merge together?
Best,
Jing

**Comment by ShunOuchi** [comment]
Hi Jing,

By specifying both HiFi and ONT reads in the -p option, both reads can be used for scaffolding.
`GreenHill -cph contig.fa -p HiFi.fastq ONT.fastq -HIC HIC_1.fastq HIC_2.fastq`

Thank you,
Shun

**Comment by JhinAir** [comment]
Thank you!
