### ISSUE TITLE
Error(3): Error, File fomat exception!! Read file is unknown format.

### ISSUE THREAD

**Issue by ishengtsai** [ShunOuchi/GreenHill#14]
Hi,

I tried to run greenhill but have encountered some error after minimap2, please suggest:

`greenhill -t 8 -o flye30x -cph ../ref.fa -p /mnt/nas2/ijt/squid/raw_data/30X.fq.gz -HIC LGH23-ON01_1_S1_L001_R1_001.fastq.gz LGH23-ON01_1_S1_L001_R2_001.fastq.gz LGH23-ON01_2_S2_L001_R1_001.fastq.gz LGH23-ON01_2_S2_L001_R2_001.fastq.gz LGH23-ON01_3_S3_L001_R1_001.fastq.gz LGH23-ON01_3_S3_L001_R2_001.fastq.gz`

Log:

minimap2 finished.
micing bubble scaffolds ...
initConsensusNode
finish initConsensuNode
delete repeat consensusnode
TOTAL_NUM_DELETE: 9395
writing scaffold and bubble files...
finish mince
Error(3): Error, File fomat exception!!
Read file is unknown format.

All the fastq seems okay? Please suggest.

**Comment by ShunOuchi** [comment]
Hi,

GreenHill checks the first read of the file and if it contains any characters other than "ATGCN", it is not recognized as a fastq. Please make sure that there are no other characters  in the file. If there are lowercase characters (i.e. "atgcn") in the file, please change the letters to upper case using tools such as [seqkit](https://github.com/shenwei356/seqkit).

Thank you,
Shun

**Comment by ishengtsai** [comment]
Many thanks for the quick reply! I was wondering which file it checks after the minimap2 stage? The fastq files seem fine. Could it be that there is a space in the name of the sequence (between 1019" "2:N)?

@VH00427:96:AACCYLHM5:1:1101:61802:1019 2:N:0:CAGACACT+NGCTGTCA
ATTTTTCCACATGGAGGAATTCAACGAGACAACTCTGCACTCATATTAAATGTCCGGTGATCAGCTCTGGATCTTTTTTTCCGTCCCTGAGCCAGGTCTTTTGTTCAGTGAAATGGCGAACATATTTTGAATGGCTCGAAGGACGAACCAG
+
-CCCCCCCCCCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCCC;CCCC-C-CCCCCCCCCC;CCC;CCCCCCCCCCCC-CCCCCCC-;CCCCCCCCCCCCC;-;CC;C;C;CC;CCCCCCCCCCCCCC;CC-C-C-CCC--CC;CCC;CCCC

Also another feature request, if the mince is run successfully. GreenHill may have a option to check to rerun after it's left off?

**Comment by ShunOuchi** [comment]
After mince finishes, both long read and Hi-C read are checked, and then mapping is performed.
The read shown above may be Hi-C, but please check the long read as well.

Thank you for your feature request. GreenHill does not currently have a option to check if mince has been successfully executed at this time, and we will consider this in a future update. 
You can check if the mince worked by checking if prefix_minced_nonBubble.fa, prefix_minced_primaryBubble.fa, and prefix_minced_secondaryBubble.fa are created. If you want to rerun GreenHill from mince results, you can run GreenHill as below;
`greenhill -c prefix_minced_nonBubble.fa -b prefix_minced_primaryBubble.fa prefix_minced_secondaryBubble.fa -o prefix -p longread.fastq -HIC HIC_1.fastq HIC_2.fastq`

**Comment by ishengtsai** [comment]
Hi,

I have started from mince results and it seems fine. So maybe it's a bug?


`greenhill -c flye30x_minced_nonBubble.fa -b flye30x_minced_primaryBubble.fa flye30x_minced_secondaryBubble.fa -o prefix -p /mnt/nas2/ijt/squid/raw_data/30X.fq.gz -HIC LGH23-ON01_1_S1_L001_R1_001.fastq.gz LGH23-ON01_1_S1_L001_R2_001.fastq.gz LGH23-ON01_2_S2_L001_R1_001.fastq.gz LGH23-ON01_2_S2_L001_R2_001.fastq.gz LGH23-ON01_3_S3_L001_R1_001.fastq.gz LGH23-ON01_3_S3_L001_R2_001.fastq.gz
`
Current log:

K=32, making hash table...

**Comment by ShunOuchi** [comment]
It may be a bug, but I don't know the cause. If you don't mind, could you send me the data you used?
(https://www.kyo-u.cloud).

**Comment by ishengtsai** [comment]
How about if I `head` the start of every file and upload to you?

**Comment by ShunOuchi** [comment]
If the bug can be reproduced with only the `head` the start of every file, that is fine.

**Comment by SanSanMX** [comment]
Sorry to reopen this issue, but I have a similar problem that I haven't been able to solve. Do you have any suggestions @ShunOuchi ?

```
greenhill -cph ../ensamble/nd.asm.fasta -p ../corrected/corrected_reads.fasta -HIC ../hic/HiCMX_CKDL23.......

Executing minimap2 ...
cat  ../ensamble/nd.asm.fasta | minimap2 -c  -t 40 -  -D --secondary=no ../ensamble/nd.asm.fasta | sort -s -k 1,1 -T . >out_selfAlignment.tsv


[M::mm_idx_gen::33.433*1.51] collected minimizers
[M::mm_idx_gen::34.631*2.62] sorted minimizers
[M::main::34.631*2.62] loaded/built the index for 73 target sequence(s)
[M::mm_mapopt_update::36.418*2.54] mid_occ = 1337
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 73
[M::mm_idx_stat::37.603*2.50] distinct minimizers: 66728105 (42.71% are singletons); average occurrences: 6.407; average spacing: 5.341; total length: 2283304613
minimap2 finished.
micing bubble scaffolds ...
initConsensusNode
finish initConsensuNode
delete repeat consensusnode
TOTAL_NUM_DELETE: 0
writing scaffold and bubble files...
finish mince
Error(3): Error, File fomat exception!!
Read file is unknown format.
```

**Comment by ShunOuchi** [comment]
@SanSanMX 

Thank you for reporting the bug. Since we're unsure of the cause, could you please run it again using the branch with the added logs(https://github.com/ShunOuchi/GreenHill/tree/14-format-error-bug-debug) and let us know the results?

```
git checkout 14-format-error-bug-debug
cd src
make
# run GreenHill
./greenhill ...
```

Also, please try starting from the mince results using the steps below.

>You can check if the mince worked by checking if prefix_minced_nonBubble.fa, prefix_minced_primaryBubble.fa, and prefix_minced_secondaryBubble.fa are created. If you want to rerun GreenHill from mince results, you can run GreenHill as below;
```
greenhill -c prefix_minced_nonBubble.fa -b prefix_minced_primaryBubble.fa prefix_minced_secondaryBubble.fa -o prefix -p longread.fastq -HIC HIC_1.fastq HIC_2.fastq
```
