### ISSUE TITLE
Hifiasm's output for greenhill

### ISSUE THREAD

**Issue by qukunjing** [ShunOuchi/GreenHill#15]
Hi,
If I am using hifiasm's results, then I have three genomes, primary, hap1 and hap2; which model should I use?
Should I use this parameter? Or please give me some advices?
```greenhill -c genome/hifiasm.hic.p_ctg.fa -b genome/hifiasm.hic.hap1.p_ctg.fa genome/hifiasm.hic.hap2.p_ctg.fa -p hifi/all.fasta.gz -HIC hic/CS_R1.fastq.gz hic/CS_R2.fastq.gz```
Thank you,
Kunjing

**Comment by ShunOuchi** [comment]
Hi, Kunjing

If you want to use hifiasm's results, then you have three choices.
1.  Using p_utg.fa
Please run GreenHill using the -cph option with the unitig of hifiasm as input. 
Hifiasm's unitig does not have any correspondence between haplotypes, so by using the -cph option, GreenHill performs self-alignment and mapping between haplotypes, followed by scaffolding and phasing.
`greenhill -cph hifiasm.hic.p_utg.fa -p HiFi.fq -HIC HIC_1.fq HIC_2.fq`

2. Using hap1 + hap2 (using hifiasm Hi-C mode result)
Please run GreenHill using the -cph option with the hap1 + hap2 of hifiasm as input. 
Hifiasm Hi-C mode generates longer unitig using Hi-C. (hifiasm.hic.hap1.p_ctg.fa, hifiasm.hic.hap2.p_ctg.fa are generated).
But hifiasm's hap1 and hap2 does not have any correspondence between haplotypes, so by using the -cph option, GreenHill performs self-alignment and mapping between haplotypes, followed by scaffolding and phasing.
`greenhill -cph hifiasm.hic.hap1.p_ctg.fa hifiasm.hic.hap2.p_ctg.fa -p HiFi.fq -HIC HIC_1.fq HIC_2.fq`

3. Using p_ctg.fa (not phasing only scaffolding)
If you don't need to generate haplotype-aware genome, please run GreenHill using the -c option with the primary contig of hifiasm as input.  In this case, use out.ConsensusOutput.fa as the final result.
`greenhill -c hifiasm.hic.p_ctg.fa -p HiFi.fq -HIC HIC_1.fq HIC_2.fq`

If you want to create a haplotype-aware genome, I recommend option 2.

Thank you,
Shun
