### ISSUE TITLE
greenhill continues after minimap2 got killed

### ISSUE THREAD

**Issue by chregu1971** [ShunOuchi/GreenHill#18]
Hi,
I tried to use greenhill to scaffold a 1.5 Gb genome, but my analysis is running out of memory.
The first mapping step (hap1 against hap2) uses more than 192 Gb of memory.
This kills minimap2 at this step, but greenhill is continuing the analysis with an empty mapping file, i.e.
no overlaps between the two haplotypes:

[M::mm_idx_stat::65.057*2.30] distinct minimizers: 49949160 (16.91% are singletons); average occurrences: 11.072; average spacing: 5.311; total length: 2936997308
Killed
minimap2 finished.
micing bubble scaffolds ...
initConsensusNode
finish initConsensuNode
delete repeat consensusnode
TOTAL_NUM_DELETE: 0
writing scaffold and bubble files...
finish mince
K=32, making hash table...

Is this the desired behaviour? How reliable will the scaffolding be if I continue?
There is also a typo in the log: I think it should be 'mincing bubble scaffolds' and not 'micing'.

Best regards,
Christian

**Comment by ShunOuchi** [comment]
Hi Christian,

> This kills minimap2 at this step, but greenhill is continuing the analysis with an empty mapping file.
Is this the desired behaviour? How reliable will the scaffolding be if I continue?

That is not the desired behavior. If minimap2 fails, GreenHill should also stop. Please run GreenHill again from the beginning.

> here is also a typo in the log: I think it should be 'mincing bubble scaffolds' and not 'micing'.

Thanks for reporting the typo, I fixed it.

Thank you,
Shun
