### ISSUE TITLE
minimap2 self mapping step use so much memory, it is unbelievable!

### ISSUE THREAD

**Issue by xiekunwhy** [ShunOuchi/GreenHill#19]
Hi,

For a 750 M genome, minimap2 self mapping step cost ~600G RAM, how greenhill make minimap2 so worse? unbelievable I think.
And minimap2 use only 10 threads even -t 40.
![image](https://github.com/ShunOuchi/GreenHill/assets/17738229/46c5f2ab-9755-4597-b971-fad3e05ac285)

![image](https://github.com/ShunOuchi/GreenHill/assets/17738229/e7951c08-a9fb-40e0-8a9c-b53a46685cfa)

Best,
Kun

**Comment by ShunOuchi** [comment]
Hi Kun,

Greenhill only uses minimap2 for self-alignment (-D --secondary=no) and long read mapping, and does nothing special. Therefore, we do not know the cause. Please ask at [minimap2 issues](https://github.com/lh3/minimap2/issues).

Thank you,
Shun
