### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by peiwen18** [ShunOuchi/GreenHill#20]
consensus scaffolding...
constructing consensus graph
linking scaffolds...
sorting links in contigID order...
estimating contig distances...
constructing paired de Bruijn graph using all libraries simultaneously
removing thin edges (NUM_LINK < 1) ...
TOTAL_NUM_DELETE=0
pairing bubble nodes...
removing edges from short nodes (LENGTH < 0) ...
TOTAL_NUM_DELETE=0
removing thin consensus edges (NUM_LINK < 1) & consensu edges from short consensus node (LENGTH < 0) ...
TOTAL_NUM_DELETE=0
dividing erroneous consensusnode...
NUM_DIVIDED_CONSENSUSNODE = 0
constructing consensus graph
linking scaffolds...
sorting links in contigID order...
estimating contig distances...
constructing paired de Bruijn graph using all libraries simultaneously
removing thin edges (NUM_LINK < 1) ...
TOTAL_NUM_DELETE=0
pairing bubble nodes...
removing edges from short nodes (LENGTH < 0) ...
TOTAL_NUM_DELETE=0
removing thin consensus edges (NUM_LINK < 1) & consensu edges from short consensus node (LENGTH < 0) ...
TOTAL_NUM_DELETE=0
makeHiCLink
finish makeHiCLink
numHiCNode:1383
Segmentation fault (core dumped)

Showing segmentaion fult （core dumped）after finished makeHiCLink. Could you give some suggestions? Thanks!

**Comment by ShunOuchi** [comment]
Hi peiwen18,

Sorry, the above information is not enough to determine the cause of the segmentation fault.
Could you provide us with additional information, such as what are using as input data, the entire log file, etc. ?

Thank you,
Shun

**Comment by LeoHongboWANG** [comment]
Hi @ShunOuchi 

Thank you for developing this tool. I am also experiencing the segmentation fault issue, Here are the relevant log lines:
consensus scaffolding...
constructing consensus graph
linking scaffolds...
sorting links in contigID order...
estimating contig distances...
constructing paired de Bruijn graph using all libraries simultaneously
removing thin edges (NUM_LINK < 1) ...
TOTAL_NUM_DELETE=0
pairing bubble nodes...
removing edges from short nodes (LENGTH < 0) ...
TOTAL_NUM_DELETE=0
removing thin consensus edges (NUM_LINK < 1) & consensu edges from short consensus node (LENGTH < 0) ...
TOTAL_NUM_DELETE=0
dividing erroneous consensusnode...
NUM_DIVIDED_CONSENSUSNODE = 0
constructing consensus graph
linking scaffolds...
sorting links in contigID order...
estimating contig distances...
constructing paired de Bruijn graph using all libraries simultaneously
removing thin edges (NUM_LINK < 1) ...
TOTAL_NUM_DELETE=0
pairing bubble nodes...
removing edges from short nodes (LENGTH < 0) ...
TOTAL_NUM_DELETE=0
removing thin consensus edges (NUM_LINK < 1) & consensu edges from short consensus node (LENGTH < 0) ...
TOTAL_NUM_DELETE=0
makeHiCLink
finish makeHiCLink
numHiCNode:910
constructing consensus graph
linking scaffolds...
sorting links in contigID order...
estimating contig distances...
constructing paired de Bruijn graph using all libraries simultaneously
removing thin edges (NUM_LINK < 1) ...
TOTAL_NUM_DELETE=0
pairing bubble nodes...
removing edges from short nodes (LENGTH < 0) ...
TOTAL_NUM_DELETE=0
removing thin consensus edges (NUM_LINK < 1) & consensu edges from short consensus node (LENGTH < 0) ...
TOTAL_NUM_DELETE=0
makeHiCLink
finish makeHiCLink
numHiCNode:1056
/var/spool/slurmd/job2906762/slurm_script: line 13: 3234587 Segmentation fault      greenhill -cph hifiasm.hic.hap1.p_ctg.fa hifiasm.hic.hap2.p_ctg.fa -p Hifi.fastq.gz -HIC Hic_R1.fq.gz Hic_R2.fq.gz -t 96

I was using Hifiasm(Hic model) get the contig-level genome: hifiasm -o asm --h1 Hic_R1.fq.gz   --h2 Hic_R2.fq.gz Hifi.fastq.gz -t 96 
And was using  greenhill -cph hifiasm.hic.hap1.p_ctg.fa hifiasm.hic.hap2.p_ctg.fa -p Hifi.fastq.gz -HIC Hic_R1.fq.gz Hic_R2.fq.gz -t 96

I would appreciate any suggestions you could provide. Many thanks!
Your regards,
Hongbo

**Comment by ShunOuchi** [comment]
Hi @LeoHongboWANG 

Thank you for using GreenHill and bug report.
The segmentation fault may be occurred in Hi-C Scaffolding step, but I don't know what is causing it.
If you don't mind, could you send me the data you used?

Thank you,
Shun

**Comment by LeoHongboWANG** [comment]
Hi Shun,

Thanks for helping me figure out this. Could you please send me the email address where I can send the data I've been using?

Best,
Hongbo

**Comment by ShunOuchi** [comment]
Please send to the following e-mail address: oouchi.s.aa[at]m.titech.ac.jp.
