### ISSUE TITLE
puzzled by the hic_map generated from the test_data and the pipeline

### ISSUE THREAD

**Issue by 88Zoe** [ShunOuchi/GreenHill#25]
Hi @ShunOuchi,
     Thank you for the tool. I followed your provided GreenHill scripts pipelines and inputted three sets of test data, along with installing all the necessary software. I was hoping to generate images similar to the provided example image, but unfortunately, the results I obtained differ significantly from the example image. The images from each set are as shown below, and I am quite perplexed about where the issue might be. I would greatly appreciate your insights and assistance in resolving this matter.
     Thank you.

![HiC_map_greenhill_example1](https://github.com/ShunOuchi/GreenHill/assets/108746230/a0bdb796-6347-41ba-8a5d-530fe7df9a7b)
![HiC_map_greenhill_example2](https://github.com/ShunOuchi/GreenHill/assets/108746230/4af38bd1-8daa-42e9-adc8-fbf4781c674e)
![HiC_map_greenhill_example3](https://github.com/ShunOuchi/GreenHill/assets/108746230/5eefc028-ce95-4563-b761-722ced942bd8)

**Comment by ShunOuchi** [comment]
Hi @88Zoe,

I apologize for any confusion. Nothing wrong with your results.
The example dataset is the simulated diploid dataset of _Caenorhabditis elegans_ chr1. However, the contact map image in README is the results of another organism with a larger genome size.  Therefore, the contactmap will be different. (More specifically, _C.elegans_  have lower differences between haplotypes, so fewer Hi-C reads are mapped uniquely, making the Hi-C contactmap whiter.)

Thank you,
Shun

**Comment by 88Zoe** [comment]
Thanks for your responses!

Zoe
