### ISSUE TITLE
Generating AGP file 

### ISSUE THREAD

**Issue by kiratalreja3** [ShunOuchi/GreenHill#26]
What is the best way to generate an AGP file for GreenHill scaffolded assembly? It is quite crucial for downstream analysis and curation so I was wondering the same. Thanks.

**Comment by ShunOuchi** [comment]
Sorry for the late reply.
GreenHill does not have an option to output AGP files. I would like to consider whether to output AGP files in a future update.
Currently, the only way to create an AGP file is by mapping the input contigs to the GreenHill scaffolded assembly.

Thank you.
