### ISSUE TITLE
[help for next steps] more contigs than chromosomes after greenhill

### ISSUE THREAD

**Issue by Isoris** [ShunOuchi/GreenHill#31]
Hello, thank you for making greenhill.

So from my experience it seems that the quality of scaffolds after greenhill and that the phasing seems great and better than the 3DDNA pipeline. however when I filtered for seqs of length > 0.5Mb I get a fragmented assembly. 

I have run 3DDNA after greenhill and this time I got 28 chromosomes for hap1 and 27 chr for hap0. normally it should be 28 for both right? (fronm the giemsa there is 28 pairs of visible chromosomes(another study)

So my questions are:

1. Would running the 3DDNA assembly pipeline on each haplotype separately using the out_afterphase_hap_0 and hap1 of the greenhill assembly as input damage the scaffolding?

This is what I get for now:

Greenhill (left hand side, y axis) vs greenhill followed by 3ddna assembly pipeline (x axis) 

 
![mashmap_hap0_3ddna_vs_greenhill_pi_91_200000](https://github.com/ShunOuchi/GreenHill/assets/78720716/659a4ee0-7ecc-4da7-8ebe-4e89503dab63)

and now greenhill hap0 vs hap 0

![GREENHILL_CMA_HIC_UL_hap0_vs_hap0](https://github.com/ShunOuchi/GreenHill/assets/78720716/a3662d7f-7e3c-49cf-929b-66852120182c)

greenhill hap 0 vs hap1 

![GREENHILL_CMA_HIC_UL_hap0_vs_hap1](https://github.com/ShunOuchi/GreenHill/assets/78720716/b6790bfa-6b24-4b41-b1be-98ba393c320e)

greenhill hap 1 vs hap 1 

![GREENHILL_CMA_HIC_UL_hap1_vs_hap1](https://github.com/ShunOuchi/GreenHill/assets/78720716/f46ae0fe-0b43-428d-a2e9-4630dc9fef2d)

greenhill followed by 3ddna assembly pipeline hap0 vs hap0

![3DDNA_CMA_HIC_UL_hap0_vs_hap0](https://github.com/ShunOuchi/GreenHill/assets/78720716/73aa407d-e152-4795-9d2b-1080db48c1ed)

greenhill followed by 3ddna assembly pipeline hap 0 vs hap 1

![3DDNA_CMA_HIC_UL_hap0_vs_hap1](https://github.com/ShunOuchi/GreenHill/assets/78720716/cdff6751-e611-4753-a61c-6ca0a6502f73)

greenhill followed by 3ddna assembly pipeline hap 1 vs hap 1 

![3DDNA_CMA_HIC_UL_hap1_vs_hap1](https://github.com/ShunOuchi/GreenHill/assets/78720716/d3532b00-cf19-483d-ae47-187b2a8c53a2)

here greenhill followed by 3ddna assembly pipeline vs clarias fuscus (the closest reference genome)

![mashmap_hap0_3ddna_vs_clarias_fuscus_pi_93_3000000](https://github.com/ShunOuchi/GreenHill/assets/78720716/9791fd54-562d-42d9-82b8-3263b8c1ec38)

From my understanding it seems that greenhill is not able to scaffold that much but is better than 3DDNA but maybe it would be better if we can run greenhill twice in a row ? or greenhill + 3DDNA or maybe its just the nature of the chromosome 1 which makes it difficult to guess if its a single chromosome or not because then 3DDNA says it is a single scaffold but greenhill says that the chromosome 1 of the 3ddna post greenhill is multiple chromosomes of greenhill?

What do you suggest to do? I will remap the reads and look for any signs of read clipping. 

And what about the repeats, what do you suggest to do?

Also do you have a custom plotting script for mashmap2? I could not find it in your paper. 

Thank you for much for making Greenhill it is very easy to use and powerful and useful :)

I dont ask you to do it for me but simply I would be greatful to have your opinion or any small advices :) thanks a lot in advance for your time.

**Comment by Isoris** [comment]
And so like here for just the chromosome 1 


GREENHILL ONLY Chr1 (x-axis) vs. Clarias fuscus Chr1 (y-axis)

![Clarias_fuscus_vs_greenhill-filtered_hap0_chr_1 pi95 s2000000 mashmap out](https://github.com/ShunOuchi/GreenHill/assets/78720716/9a018e9f-2ed5-4cdc-b7a7-6dde88e236f0)



GREENHILL+3DDNA assembly pipeline Chr1 (x-axis) vs. Clarias fuscus Chr1 (y-axis)


![Clarias_fuscus_vs_greenhill-and-3ddna-filtered_hap0_chr_1 pi95 s2000000 mashmap out](https://github.com/ShunOuchi/GreenHill/assets/78720716/dc5151b9-e25a-4b4c-b759-d7ad4c9a34a5)


So for me it seems that the second dotplot is better right ?

**Comment by ShunOuchi** [comment]
Hello, thank you for using GreenHill.

> Would running the 3DDNA assembly pipeline on each haplotype separately using the out_afterphase_hap_0 and hap1 of the greenhill assembly as input damage the scaffolding?

Not all hap0 scaffolds are derived from the same haplotype in GreenHill results. Therefore, scaffolding hap0 and hap1 separately with 3D-DNA may result in scaffolds containing switch errors.

> What do you suggest to do?

It is difficult to create a perfect chromosome-level scaffolds using 3D-DNA or GreenHill, so I recommend looking at contact maps and curating scaffolds manually using [juicebox](https://github.com/aidenlab/Juicebox). Hi-C contact map can help identify scaffolding and phasing errors.
For more details, please see Manual review with Juicebox section in README and juicebox [manuals](https://github.com/aidenlab/Juicebox/wiki/Juicebox-Assembly-Tools).

> And what about the repeats, what do you suggest to do?

Constructing repeat region correctly is difficult even with Hi-C. 
If you have ultra-long reads, trying verkko or hifiasm UL mode may improve repeat region construction.
Also consider using the gap close tool (such as [TGS-GapCloser)](https://github.com/BGI-Qingdao/TGS-GapCloser) to fill in the gaps after Hi-C Scaffolding.

> Also do you have a custom plotting script for mashmap2?

There is no custom script for mashmap2. Sorry.


Thank you.

**Comment by Isoris** [comment]
Hello, thanks for the answers, 

Actually after greenhill and also 3DDNA I get those maps:

Does that means that everything is scaffolded at the maximum (no red in TRANS) but red in CIS:

![image](https://github.com/ShunOuchi/GreenHill/assets/78720716/60165193-fe44-4d0e-b904-12fd0b46f43e)


my contigs are 47 Mb long for Chr1 however when use quartet assemblymapper and map back the Hifiasm Haplotype 0 (.hap1) UL HIC contigs on the Greenhill out hap0 the Chr1 goes from 47 Mb to 80 Mb it is like if Greenhill stopped at the middle of the Chr1 or like if it deduplicated the 3' of the Chr1. and When I look into IGV for ONT, NGS and HIFI I get this at the end of Chr1:

![image](https://github.com/ShunOuchi/GreenHill/assets/78720716/b0d351b6-aa46-45a4-9e5b-a90af3e6bc7e)


it seems strange that the chromosome is still continuing for more than 1000 bases and that for HIFI the coverage is still high at the Chr1 tail 

What do you think?

**Comment by ShunOuchi** [comment]
> my contigs are 47 Mb long for Chr1 however when use quartet assemblymapper and map back the Hifiasm Haplotype 0 (.hap1) UL HIC contigs on the Greenhill out hap0 the Chr1 goes from 47 Mb to 80 Mb it is like if Greenhill stopped at the middle of the Chr1 or like if it deduplicated the 3' of the Chr1.

I'm not familiar with the quarTeT AssemblyMapper, so I can't say anything accurate. Are you mapping hifiasm hic.hap1.p_ctg to GreenHill's result chr1_hap0 ? If so, the increase in total size from 47 Mb to 80 Mb is a mystery.

> it seems strange that the chromosome is still continuing for more than 1000 bases and that for HIFI the coverage is still high at the Chr1 tail

From the IGV snapshot, chr1 is still considered to be continuing. There may be contigs derived from chr1 that was not incorporated into the chr1 scaffold. I think the contact map above is drawn with large scaffolds only, do you have a contact map drawn with all scaffolds, including the smaller scaffolds? Please check if there is small scaffolds that have contact with the chr1 scaffold.

Thank you.

**Comment by Isoris** [comment]
Yes, if not mistake from my side I've mapped the same haplotype again to only Chromosome 1 (47Mb) and this Chr1 didnt show any link in TRANS in the Hi-C map. After the AssemblyMapper of QUARTET the Chr1 increased from 47Mb to 87MB. 

I will:

1. Assembly with VERKKO and try to see whats happening.

2. Juicer pre to regenerate the HIC map without -q 28 to allow for no filtering in the post review and look for any link in TRANS between the Chr1 (47Mb) and the smaller scaffolds >100,000bp.

3. Align nanopore and HIFI and SR and look at IGV for the Chr1 (87Mb) 

4. Use winnowmap to map the nanopore and look at IGV for the Chr1 (87Mb)

I will update you.

Thank you for your help.

**Comment by Isoris** [comment]
This is what I find for 3. 

![image](https://github.com/ShunOuchi/GreenHill/assets/78720716/787b8b17-bc23-436c-8f6c-3a4ad2b923c5)


What do you think?

Thank you in advance. :)

**Comment by Isoris** [comment]
So this is what I find when I look at the links in TRANS for Hi-C scaffold (chr1) for the Greenhill + 3DDNA assembly:

![image](https://github.com/ShunOuchi/GreenHill/assets/78720716/efd66c8f-25c5-4253-a129-803eb05af72e)


From my understanding, there are links in Cis within the scaffolds indicative of a single chromosome / scaffold and no links in trans to other contigs meaning that the chromosome is indeed at its full length however from the previous IGV screens we could see the abrupt stop with the high hifi coverage. What do you think?

**Comment by Isoris** [comment]
> > my contigs are 47 Mb long for Chr1 however when use quartet assemblymapper and map back the Hifiasm Haplotype 0 (.hap1) UL HIC contigs on the Greenhill out hap0 the Chr1 goes from 47 Mb to 80 Mb it is like if Greenhill stopped at the middle of the Chr1 or like if it deduplicated the 3' of the Chr1.
> 
> I'm not familiar with the quarTeT AssemblyMapper, so I can't say anything accurate. Are you mapping hifiasm hic.hap1.p_ctg to GreenHill's result chr1_hap0 ? If so, the increase in chr1 size from 47 Mb to 80 Mb is a mystery.
> 
> > it seems strange that the chromosome is still continuing for more than 1000 bases and that for HIFI the coverage is still high at the Chr1 tail
> 
> From the IGV snapshot, chr1 is still considered to be continuing. There may be contigs derived from chr1 that was not incorporated into the chr1 scaffold. I think the contact map above is drawn with large scaffolds only, do you have a contact map drawn with all scaffolds, including the smaller scaffolds? Please check if there is small scaffolds that have contact with the chr1 scaffold.

Heres the only things that I can see 

![image](https://github.com/ShunOuchi/GreenHill/assets/78720716/91a3dfb6-9e81-47a6-bf04-f7a1cd9b6ead)


![image](https://github.com/ShunOuchi/GreenHill/assets/78720716/f1b75137-5710-4c39-b852-1e93c4154339)

> Thank you.

**Comment by Isoris** [comment]
![image](https://github.com/ShunOuchi/GreenHill/assets/78720716/c3563aa6-7578-4a46-92d6-5cbfec2a74da)

**Comment by ShunOuchi** [comment]
Considering the length of Clara's fuscus chr1 and the contact map, I think that almost the entire length of chr1 are constructed. However, based on the IGV results, I think that chr1 is not constructed to the end of chromosome. There may be contigs removed as redundant by GreenHill due to repeat sequences, etc.

**Comment by Isoris** [comment]
I tend to agree and it is supported by the fact that the end of the 87 Mb chromosome is full of structural errors. 

So I will start back from GreenHill scaffolds and fill the gaps in the 47 Mb chromosome with TGS gapcloser.


Thank you so much for your advices. it helped me. :)
