### ISSUE TITLE
How to edit the assembly in the juicebox app?

### ISSUE THREAD

**Issue by Isoris** [ShunOuchi/GreenHill#32]
Hello,

I have finished running GreenHill and I separated the haplotypes based on hap0 and hap1 then after running  juicer pre -s "DpnII" followed by run asm visualizer from the aiden lab, I get inter.hic in the aligned folder, base.fa base.assembly and base.ctg_info.assembly 

I would like to know how to manually edit the assembly, we need to rename the inter.hic into base.hic then open it as a map on juicebox and also open the base.assembly in the juicebox and then export to modified assembly file and run the post-review, is that correct?

Could you please briefly explain how do you load the data and perform the manual curation of scaffolds within chromosome boundaries because I don't understand what steps to perform and in which order. . 

```
#! /bin/bash
#SBATCH -p memory
#SBATCH -N 1 -n 80
#SBATCH --mem=120GB
#SBATCH -t 5-00:00:00
#SBATCH -A proj5034
#SBATCH -J review_greenhill_with_juicer_CMA

source ~/.bashrc
mamba activate /tarafs/data/project/proj5057-AGBKUB/13-programs/env

path_juicer="/tarafs/data/project/proj5057-AGBKUB/13-programs/juicer/CPU"
path_3d="/tarafs/data/project/proj5057-AGBKUB/15-pipelines/3d-dna-201008"
path_greenhill="/tarafs/data/project/proj5057-AGBKUB/13-programs/GreenHill-1.1.0"

echo "$path_juicer"
echo "$path_3d"
echo "$path_greenhill"

seqkit sort -lr query/GREENHILL_CMA_HIC_UL_hap0.filtered100000.fa >base.fa
bwa index base.fa >bwa_index.log 2>&1
seqkit fx2tab -nl base.fa >base.sizes

juicer.sh -D $path_juicer -d $PWD -g base -s "DpnII" -z base.fa -p base.sizes >juicer.log.o 2>juicer.log.e
awk -f ${path_3d}/utils/generate-assembly-file-from-fasta.awk base.fa >base.assembly 2>generate.log.e
${path_3d}/visualize/run-assembly-visualizer.sh base.assembly aligned/merged_nodups.txt >visualizer.log.o 2>visualizer.log.e
python ${path_greenhill}/utils/fasta_to_juicebox_assembly.py base.fa >base.ctg_info.assembly
```

 Thank you very much in advance for your help. 
 Quentin.

**Comment by ShunOuchi** [comment]
Please load base.hic and base.ctg_info.assembly in Juicebox and make the modifications manually. Then export the review assembly and create a fasta file with run-asm-pipeline-post-review.sh.

Thank you

**Comment by Isoris** [comment]
So I need to juicer pre to get base.hic right? 

Ok thank you I will try and let you know if that works well for me thank you much. 😁🙏🏻

**Comment by Isoris** [comment]
It worked well thank you ! 😁 

Also I have another question, if Juicebox JBAT crashes during the modifications or if we want to modify the assembly in two different sessions, after we export the base.modif.assembly we can't reload it with the base .hic because the assembly file will not overlap the hic maps anymore. 

So we need to export assembly to fasta and then redo all of the pipeline that you have shared with juicer pre and generate assembly from fasta everytime , when we modify and export the new assembly file right ?

Like if I modify the assembly, save it (export modified assembly) but suddenly Juicebox crashes. Do I need to redo all the HiC mapping on the new fasta from the modified assembly ?  Before being able to edit it again?

I don't know how to explain clearly, I hope you can understand me.



The last question is related to haplotypes, we use 1 haplotype for the base fa right, so do we need to make the two haplotypes separately or just choose any of the two arbitrarily, loose a bit of genome information but still be able to publish it as genome assembly, haploid collapsed on NCBI genomes?


Thank you for your answers and thank you again for making Greenhill. 

Another comment that I want to point out is that for me Greenhill is outperforming 3DDNA based on QV, and structural accuracy and phasing. But when the assembly is diploid or hetorozygous ( for instance if the species is an hybrid) I saw that greenhill will not be able to merge and will duplicate the scaffolds.

 It seems that for hybrid species with two parental haplotypes from two different species greenhill is not able to merge the scaffold as well as the 3DDNA does for very heterozygous genomes.


For me after using both tools I think that although greenhill is better for phasing, it is not good at merging scaffolds as well as 3ddna does. I think that It is because it doesn't.implement a diploid mode with LastZ alignments. But also that in 3DDNA we can choose the number of iterations but in greenhill I see that for my hybrid catfish ( cross of two species) the scaffolds are of high quality but it's very very fragmented and deduplicated. 

I am not a specialist but I think that it would be beneficial if you could for instance implement some fast way to have the synteny of genes to better dissociate between two chromosomes of two species which are very similar but yet should be separated because sometimes the HIC reads will map onto both even though they should map on either one haplotype or on the other.

Maybe if you can use the synteny like using pangene instead of LastZ or something.. idk..  because the strength of Greenhill is that the phasing is done with all types of reads. But it needs more tuning when sometimes the chromosomes are so similar that it seems thay greenhill will map hic on the two chromosomes of two species even though it should map on either, and so it will duplicate the scaffolds?



Thank you anyway. You saved me. ✌🏻🙏🏻😁

**Comment by Isoris** [comment]
Hi again, 

In another post you suggested to use the out_Afterphase.fa for juicer pre.

Here's what I have got:

![image](https://github.com/ShunOuchi/GreenHill/assets/78720716/4d5f7c77-a9d1-4348-85ce-092fc5168469)


You see for some pairs of pseudochromosomes for instance ChrA from haplotype0 will interact with ChrA' from haplotype1 so it means that the assembly is correct.

But for some pairs of pseudochromosomes there is no HiC interractions (is it a gap?) and also some pseudochromosomes boundaries in blue are not aligned on the HiC map interractions?

1. AM I supposed to remove the gaps (the green boundaries in which there is no red HiC interractions? or is it cause by the inability of HiC to map on the Centromeres? which I dont believe because in the Other HiC experiments ive never seen anything like that)
![image](https://github.com/ShunOuchi/GreenHill/assets/78720716/6d625fbf-8bbe-4576-8414-66e7133ca93d)

2. For the small scaffolds in blue on the lower right (which are small chunks and not assembled debris but which have interractions with both haplotypes: AM I supposed to move them in the chromosomes? and so I need to duplicate them? Or Do I need to work only on each haplotype separately but use the Out_afterphase base.hic as a blueprint?

![image](https://github.com/ShunOuchi/GreenHill/assets/78720716/29fc2ffa-f6a4-44b8-96dd-e0641be70e36)


Thanks in advance for your help.

**Comment by Isoris** [comment]
> Please load base.hic and base.ctg_info.assembly in Juicebox and make the modifications manually. Then export the review assembly and create a fasta file with run-asm-pipeline-post-review.sh.
> 
> Thank you

Hi, Also when I did the steps you suggested:

Juicer pre to get merged_dedups.txt

run_assembly_visualizer.sh to get the base.hic files

and the custom script to get the base.ctg info, i got those files:

![image](https://github.com/ShunOuchi/GreenHill/assets/78720716/b12cab35-915d-46e5-94d7-2406576160b9)


However the base.hic maps seems not to match with the .assembly file in the sense that although the boundaries of the assembly files overlap the hic map correctly, when I manually edit the assembly file during the review process in juicebox JBAT v2.16.00 the hic red links do not actively change. 


My question is not so related with GreenHill but i'm trying to undertstand how to make sense of the ctg.info.assembly that you used. Thank you again

**Comment by ShunOuchi** [comment]
> But for some pairs of pseudochromosomes there is no HiC interractions (is it a gap?) and also some pseudochromosomes boundaries in blue are not aligned on the HiC map interractions?
AM I supposed to remove the gaps (the green boundaries in which there is no red HiC interractions? or is it cause by the inability of HiC to map on the Centromeres? which I dont believe because in the Other HiC experiments ive never seen anything like that)

The reason there is no red Hi-C interractions is that juicer's mapping results do not include MAPQ＝0 results (i.e. non-unique mapping results). In the case of haplotype resolved genomes, there are regions that appear to have no Hi-C interactions because Hi-C reads cannot uniquely map to the regions with high homology between haplotypes (not constructed separately in GreenHill). If you remap Hi-C with MAPQ≥0, you will see that they are not a GAP.

>For the small scaffolds in blue on the lower right (which are small chunks and not assembled debris but which have interractions with both haplotypes: AM I supposed to move them in the chromosomes? and so I need to duplicate them? Or Do I need to work only on each haplotype separately but use the Out_afterphase base.hic as a blueprint?

Such contigs should be determined to be duplicated based on their coverage. If coverage is homo, the contig should be duplicated and moved to both haplotypes. If coverage is hetero, the contig should be moved to only one haplotype.

Thank you

**Comment by Isoris** [comment]
> > But for some pairs of pseudochromosomes there is no HiC interractions (is it a gap?) and also some pseudochromosomes boundaries in blue are not aligned on the HiC map interractions?
> > AM I supposed to remove the gaps (the green boundaries in which there is no red HiC interractions? or is it cause by the inability of HiC to map on the Centromeres? which I dont believe because in the Other HiC experiments ive never seen anything like that)
> 
> The reason there is no red Hi-C interractions is that juicer's mapping results do not include MAPQ＝0 results (i.e. non-unique mapping results). In the case of haplotype resolved genomes, there are regions that appear to have no Hi-C interactions because Hi-C reads cannot uniquely map to the regions with high homology between haplotypes (not constructed separately in GreenHill). If you remap Hi-C with MAPQ≥0, you will see that they are not a GAP.
> 
> > For the small scaffolds in blue on the lower right (which are small chunks and not assembled debris but which have interractions with both haplotypes: AM I supposed to move them in the chromosomes? and so I need to duplicate them? Or Do I need to work only on each haplotype separately but use the Out_afterphase base.hic as a blueprint?
> 
> Such contigs should be determined to be duplicated based on their coverage. If coverage is homo, the contig should be duplicated and moved to both haplotypes. If coverage is hetero, the contig should be moved to only one haplotype.
> 
> Thank you

Hello, Thank you for the answer, and do you recommend editing the HiC map on separate haplotypes or directly in the out_final file? I tried to do it and it was quite long can I also do it separately for hap0 and hap1? is it the same ? Ok I will tell you once i'm done but for now It looks very good thank you so much for your help.
