### ISSUE TITLE
Preprocessing of Hi-C reads

### ISSUE THREAD

**Issue by S-111** [ShunOuchi/GreenHill#34]
I assembled a genome using hifiasm's Hi-C mode with HiFi reads and Hi-C reads. The Hi-C reads used were raw data. 
In this case, before running GreenHill, should I map the Hi-C reads to the assembled genome, extract valid reads, and then use only the valid reads for scaffolding?

**Comment by ShunOuchi** [comment]
I think that if raw reads are used for scaffolding, the results may be not much different than if only valid read are used. So, I think that it is unnecessary to extract and use only valid reads for scaffolding.

Thank you

**Comment by S-111** [comment]
OK, I understand.
Thank you very much for your answer!

**Comment by S-111** [comment]
OK, I understand.
Thank you very much for your answer!
