### ISSUE TITLE
Using HiFi + Hi-C Hifiasm assembly as input 

### ISSUE THREAD

**Issue by foreignsand** [ShunOuchi/GreenHill#37]
Apologies if this is covered somewhere and I missed it, but I couldn't find information about using a phased HiFi + Hi-C Hifiasm assembly as input for GreenHill. Would it be considered haplotype-aware style input?

Many thanks!

**Comment by ShunOuchi** [comment]
Briefly, I recommend to run GreenHill using the -cph option with the hap1 + hap2 of hifiasm as input.
```
greenhill -cph hifiasm.hic.hap1.p_ctg.fa hifiasm.hic.hap2.p_ctg.fa -p HiFi.fq -HIC HIC_1.fq HIC_2.fq
```

Please see https://github.com/ShunOuchi/GreenHill/issues/15#issuecomment-1647277283 for details.

Thank you
